spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/xiheo2o?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false
      username: root
      password: root

      ## 连接池配置
      initial-size: 5
      max-active: 60
      max-wait: 6000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query-timeout: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
soul:
  dubbo:
    admin-url: http://localhost:9095
    context-path: /xihe
    app-name: xiheo2o