spring:
  profiles:
    active: @env@
  application:
    name: xiheo2o
dubbo:
  application:
    name: xiheo2o
  scan:
    base-packages: com.stb.xiheo2o.center
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
